export const COUNTRY_CODES = [
  { code: "+63", country: "PH", label: "🇵🇭 +63 Philippines" },
  { code: "+1", country: "US", label: "🇺🇸 +1 United States / Canada" },
  { code: "+81", country: "JP", label: "🇯🇵 +81 Japan" },
  { code: "+82", country: "KR", label: "🇰🇷 +82 South Korea" },
  { code: "+86", country: "CN", label: "🇨🇳 +86 China" },
  { code: "+852", country: "HK", label: "🇭🇰 +852 Hong Kong" },
  { code: "+886", country: "TW", label: "🇹🇼 +886 Taiwan" },
  { code: "+65", country: "SG", label: "🇸🇬 +65 Singapore" },
  { code: "+60", country: "MY", label: "🇲🇾 +60 Malaysia" },
  { code: "+66", country: "TH", label: "🇹🇭 +66 Thailand" },
  { code: "+84", country: "VN", label: "🇻🇳 +84 Vietnam" },
  { code: "+62", country: "ID", label: "🇮🇩 +62 Indonesia" },
  { code: "+91", country: "IN", label: "🇮🇳 +91 India" },
  { code: "+61", country: "AU", label: "🇦🇺 +61 Australia" },
  { code: "+64", country: "NZ", label: "🇳🇿 +64 New Zealand" },
  { code: "+44", country: "GB", label: "🇬🇧 +44 United Kingdom" },
  { code: "+49", country: "DE", label: "🇩🇪 +49 Germany" },
  { code: "+33", country: "FR", label: "🇫🇷 +33 France" },
  { code: "+39", country: "IT", label: "🇮🇹 +39 Italy" },
  { code: "+34", country: "ES", label: "🇪🇸 +34 Spain" },
  { code: "+31", country: "NL", label: "🇳🇱 +31 Netherlands" },
  { code: "+41", country: "CH", label: "🇨🇭 +41 Switzerland" },
  { code: "+7", country: "RU", label: "🇷🇺 +7 Russia" },
  { code: "+971", country: "AE", label: "🇦🇪 +971 United Arab Emirates" },
  { code: "+966", country: "SA", label: "🇸🇦 +966 Saudi Arabia" },
  { code: "+55", country: "BR", label: "🇧🇷 +55 Brazil" },
  { code: "+52", country: "MX", label: "🇲🇽 +52 Mexico" },
  { code: "+27", country: "ZA", label: "🇿🇦 +27 South Africa" },
];

export const DEFAULT_COUNTRY_CODE = "+63";
